version: '3.3'
services:
  mysql:
    build: ./environments/development/docker/mysql
    container_name: instabot_mysql
    ports:
      - "33064:3306"
    environment:
      MYSQL_ROOT_PASSWORD: instabot
      MYSQL_DATABASE: instabot
      MYSQL_USER: instabot
      MYSQL_PASSWORD: instabot

  phpfpm:
    build: ./environments/development/docker/php
    links:
     - mysql:mysql
    expose:
      - "9000"
    volumes:
     - ./environments/development/docker/php/php.ini:/usr/local/etc/php/php.ini
     - ./:/var/www/html
    entrypoint: dockerize -wait tcp://mysql:3306 -timeout 120s
    command: php-fpm

  cron:
    build: ./environments/development/docker/php
    links:
     - mysql:mysql
    volumes:
     - ./environments/development/docker/php/config/cron/crontab.tmpl:/etc/cron.d/crontab
     - ./environments/development/docker/php/bin/cron-entrypoint.sh:/usr/local/bin/cron-entrypoint.sh
     - ./environments/development/docker/php/php.ini:/usr/local/etc/php/php.ini
     - ./:/var/www/html
    entrypoint: cron-entrypoint.sh
    command: ["cron", "-f"]

  nginx:
    build: ./environments/development/docker/nginx
    links:
      - phpfpm:phpfpm
    expose:
      - "80"
    volumes:
      - ./environments/development/docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./:/var/www/html
    environment:
      VIRTUAL_HOST: instabot.local
    networks:
      default:
        aliases:
          - instabot.local

  mailcatcher:
      image: schickling/mailcatcher
      ports:
       - "1080:1080"

  redis:
    build: ./environments/development/docker/redis
    ports:
      - "63790:6379"
    volumes:
      - ./storage/redis:/data
      - ./environments/development/redis/redis.conf:/usr/local/etc/redis/redis.conf
    entrypoint:
      - redis-server
      - "--appendonly yes"

  laravel-horizon-listener:
    build: ./environments/development/docker/php
    links:
      - redis
    expose:
      - "9000"
    volumes:
      - ./:/var/www/html
    command: php artisan horizon

networks:
  default:
    external:
      name: instabot
